export const UPDATE_PROCESS_INFO = 'UPDATE_PROCESS_INFO';
export const UPDATE_CPU_INFO = 'UPDATE_CPU_INFO';
export const UPDATE_CPU_LOAD = 'UPDATE_CPU_LOAD';
export const UPDATE_MEMORY_LAYOUT = 'UPDATE_MEMORY_LAYOUT';
export const UPDATE_MEMORY_LOAD = 'UPDATE_MEMORY_LOAD';
export const UPDATE_DISK_INFO = 'UPDATE_DISK_INFO';
export const PROCESS_KILLED = 'PROCESS_KILLED';