export const UPDATE_PROCESS_INFO = 'UPDATE_PROCESS_INFO';
export const UPDATE_CPU_INFO = 'UPDATE_CPU_INFO';
export const UPDATE_CPU_LOAD = 'UPDATE_CPU_LOAD';
export const UPDATE_CPU_CURRENT_SPEED = 'UPDATE_CPU_CURRENT_SPEED';
export const UPDATE_MEMORY_INFO = 'UPDATE_MEMORY_INFO';
export const UPDATE_MEMORY_LOAD = 'UPDATE_MEMORY_LOAD';
export const UPDATE_DISK_LOAD = 'UPDATE_DISK_LOAD';
export const PROCESS_KILLED = 'PROCESS_KILLED';